INSERT INTO CUSTOMER (ID, NAME, LASTNAME) VALUES ('1', 'NAMEONE', 'LASTNAME');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME) VALUES ('2', 'NAMETWO', 'LASTNAME');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME) VALUES ('3', 'NAMETHREE', 'LASTNAME');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME) VALUES ('4', 'NAMEFOUR', 'LASTNAME');
