INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS) VALUES ('1', 'NAMEONE', 'LASTNAME', 'ACTIVE');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS) VALUES ('2', 'NAMETWO', 'LASTNAME', 'ACTIVE');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS) VALUES ('3', 'NAMETHREE', 'LASTNAME', 'INACTIVE');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS) VALUES ('4', 'NAMEFOUR', 'LASTNAME', 'INACTIVE');
