INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, POSTAL_CODE) VALUES (5, 'STREET NAME', '1', 'SUBURBONE', '1234');
INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, POSTAL_CODE) VALUES (6, 'STREET NAME', '2', 'SUBURBTWO', '1234');
INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, POSTAL_CODE) VALUES (7, 'STREET NAME', '3', 'SUBURBTHREE', '1234');
INSERT INTO ADDRESS (ID, STREET, NUMBER, SUBURB, POSTAL_CODE) VALUES (8, 'STREET NAME', '4', 'SUBURBFOUR', '1234');
INSERT INTO CONTACT (ID, EMAIL, PHONE) VALUES (9, 'TEST@TEST.COM', '2387346784');
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS, ADDRESS_ID, CONTACT_ID) VALUES ('1', 'NAMEONE', 'LASTNAME', 'ACTIVE', 5, 9);
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS, ADDRESS_ID) VALUES ('2', 'NAMETWO', 'LASTNAME', 'ACTIVE', 6);
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS, ADDRESS_ID) VALUES ('3', 'NAMETHREE', 'LASTNAME', 'INACTIVE', 7);
INSERT INTO CUSTOMER (ID, NAME, LASTNAME, STATUS, ADDRESS_ID) VALUES ('4', 'NAMEFOUR', 'LASTNAME', 'INACTIVE', 8);

